<?php
/**
 * 
 * A core model for statistics and analysis
 * which is called from core/controller
 * 
 */

class Statistics extends Model {

    function InsertVisit($Values) {
        $Query = 'INSERT INTO `Visits`
        (`CLIENT_TRACK`, `CONTEXT_DOCUMENT_ROOT`, `CONTEXT_PREFIX`, `DOCUMENT_ROOT`, `HTTP_ACCEPT`, `HTTP_ACCEPT_ENCODING`, `HTTP_ACCEPT_LANGUAGE`, `HTTP_CACHE_CONTROL`, `HTTP_COOKIE`, `HTTP_HOST`, `HTTP_REFERER`, `HTTP_UPGRADE_INSECURE_REQUESTS`, `HTTP_Person_AGENT`, `PATH_INFO`, `PATH_TRANSLATED`, `PHP_SELF`, `QUERY_STRING`, `REDIRECT_STATUS`, `REDIRECT_URL`, `REMOTE_ADDR`, `REMOTE_PORT`, `REQUEST_METHOD`, `REQUEST_SCHEME`, `REQUEST_TIME`, `REQUEST_TIME_FLOAT`, `REQUEST_URI`, `SCRIPT_FILENAME`, `SCRIPT_NAME`, `HTTP_CLIENT_IP`, `HTTP_X_FORWARDED_FOR`, `HTTP_USER_AGENT`, `PHP_AUTH_USER`)
        VALUES
        (:CLIENT_TRACK, :CONTEXT_DOCUMENT_ROOT, :CONTEXT_PREFIX, :DOCUMENT_ROOT, :HTTP_ACCEPT, :HTTP_ACCEPT_ENCODING, :HTTP_ACCEPT_LANGUAGE, :HTTP_CACHE_CONTROL, :HTTP_COOKIE, :HTTP_HOST, :HTTP_REFERER, :HTTP_UPGRADE_INSECURE_REQUESTS, :HTTP_Person_AGENT, :PATH_INFO, :PATH_TRANSLATED, :PHP_SELF, :QUERY_STRING, :REDIRECT_STATUS, :REDIRECT_URL, :REMOTE_ADDR, :REMOTE_PORT, :REQUEST_METHOD, :REQUEST_SCHEME, :REQUEST_TIME, :REQUEST_TIME_FLOAT, :REQUEST_URI, :SCRIPT_FILENAME, :SCRIPT_NAME, :HTTP_CLIENT_IP, :HTTP_X_FORWARDED_FOR, :HTTP_USER_AGENT, :PHP_AUTH_USER)';
        $Result = $this->DoQuery($Query, $Values);
        return $Result;
    }

}